hotfix13

diff --git a/Jenkinsfile-task3 b/Jenkinsfile-task3
--- a/Jenkinsfile-task3
+++ b/Jenkinsfile-task3
@@ -89,17 +89,26 @@ stage('Cleanup & Preparation') {
                 sshagent(['vm-ssh-key']) {
                     script {
                         sh """
-                        ssh -o StrictHostKeyChecking=no root@${params.VM_IP} "
+                        ssh -o StrictHostKeyChecking=no root@${params.VM_IP} << 'EOF'
+                            export KUBECONFIG=/root/.kube/config
+                            
                             pkill -f 'kubectl port-forward' || true
+                            sleep 1
                             
-                            nohup /usr/local/bin/kubectl port-forward --address 0.0.0.0 service/devops-app-service ${env.TARGET_PORT}:8000 > /tmp/pf.log 2>&1 & 
-                            sleep 2
-                            disown -a
+                            nohup /usr/local/bin/kubectl port-forward --address 0.0.0.0 service/devops-app-service ${env.TARGET_PORT}:8000 > /tmp/port_forward.log 2>&1 &
                             
-                            netstat -tulnp | grep ${env.TARGET_PORT} || (echo 'ПОРТ НЕ СЛУХАЄТЬСЯ!' && exit 1)
+                            sleep 3
+
+                            if ss -tulnp | grep -q ":${env.TARGET_PORT}"; then
+                                echo "SUCCESS: Port ${env.TARGET_PORT} is open and forwarding!"
+                            else
+                                echo "ERROR: Port ${env.TARGET_PORT} is NOT open. Check /tmp/port_forward.log"
+                                cat /tmp/port_forward.log
+                                exit 1
+                            fi
                             
                             /usr/local/bin/kubectl rollout status deployment/devops-app --timeout=60s
-                        "
+EOF
                         """
                     }
                 }
